name: Feature
description: Suggest an idea for this project.
title: '[Enhancement] '
labels:
  - enhancement
assignees: jonlabelle

body:
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of the problem
      placeholder: "I'm always frustrated when..."
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context or screenshots
      description: Add any additional context or screenshots about your request
    validations:
      required: false
