name: Question
description: Ask us a question.
title: '[Question] '
labels:
  - question

body:
  - type: textarea
    id: question
    attributes:
      label: What's your question?
      description: If you're not exactly sure what to say, [here are some suggestions](https://stackoverflow.com/help/how-to-ask "Go to how to ask questions on Stack Overflow")
    validations:
      required: true
